Public Class Coaches
    Inherits Personnel

    Sub New()
        'GenCoaches(CoachNum)
    End Sub

    Public Sub GenCoaches(ByVal coachNum As Integer, ByVal xCoach As Coaches, coachDT As DataTable)

        xCoach = New Coaches 'Initializes a new instance of the Coach
        PersonalityModel(coachDT, coachNum, xCoach)
        ' For i As Integer = 0 To NumCoaches
        coachDT.Rows.Add(coachNum)
        GenNames(coachDT, coachNum, "Coach", 0) 'Gets Name, College, Age, Experience, Height and Weight for Coaches
        'GetPersonalityStats() 'Gets Personality Stats for the coaches
        Try

            coachDT.Rows(coachNum).Item("CoachType") = GetCoachType(coachDT.Rows(coachNum).Item("Age"))
            coachDT.Rows(coachNum).Item("SideOfBall") = GetSideOfBall(coachDT.Rows(coachNum).Item("CoachType"))
            GetCoachSkills(coachDT, coachDT.Rows(coachNum).Item("CoachType"), coachNum, coachDT.Rows(coachNum).Item("SideOfBall"))
            coachDT.Rows(coachNum).Item("Experience") = MT.GenerateInt32((coachDT.Rows(coachNum).Item("Age") - 22), coachDT.Rows(coachNum).Item("Age") - 24)
            coachDT.Rows(coachNum).Item("OffPhil") = String.Format("'{0}'", GetOffPhil())
            coachDT.Rows(coachNum).Item("DefPhil") = String.Format("'{0}'", GetDefPhil())
            coachDT.Rows(coachNum).Item("ValuesST") = MT.GetGaussian(49.5, 16.5)
            coachDT.Rows(coachNum).Item("ValuesCharacter") = MT.GetGaussian(49.5, 16.5)

        Catch ex As System.ArgumentException
            Console.WriteLine(ex.Message)
            Console.WriteLine(ex.Data)
        End Try
        ' Next i
        Try
            For i As Integer = 0 To coachDT.Rows.Count - 1
                For col = 0 To coachDT.Columns.Count - 1
                    If coachDT.Rows(i).Item(col) Is DBNull.Value Then
                        coachDT.Rows(i).Item(col) = 0
                    End If
                Next col
            Next i
        Catch ex As System.IndexOutOfRangeException
            Console.WriteLine(ex.Message)
            Console.WriteLine(ex.Data)
        End Try

    End Sub
    ''' <summary>
    ''' Gets specialized skills for each type of coach
    ''' </summary>
    ''' <param name="CoachType"></param> <param name="i"></param>
    Private Sub GetCoachSkills(ByVal coachDT As DataTable, ByVal coachType As Integer, i As Integer, sideOfBall As String)
        Select Case coachType
            Case 1 'Head Coach 1
                Select Case sideOfBall
                    Case "'OFF'" 'offensive minded HC
                        coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                    Case "'DEF'"
                        coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(75, 8.33)

                    Case "'SPT'"
                        coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(75, 8.33)
                        coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                End Select
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(75, 8.33)

            Case 2 'Assistant HC 1
                Select Case sideOfBall
                    Case "'OFF'"
                        coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                    Case "'DEF'"
                        coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(25, 8.33)
                        coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(60, 8.33)
                        coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(60, 8.33)
                End Select
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(60, 8.33)

            Case 3 'OC 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(55, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(75, 8.33)

            Case 4 'DC 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(55, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(75, 8.33)

            Case 5 'Special Teams 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(55, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(50, 8.33)

            Case 6 'Asst Special Teams 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(50, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(30, 8.33)

            Case 7 'QB 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(60, 8.33)

            Case 8 'RB 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(35, 8.33)

            Case 9 'WR 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(35, 8.33)

            Case 10 'Asst WR 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(25, 8.33)

            Case 11 'TE 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(35, 8.33)

            Case 12 'OL 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(35, 8.33)

            Case 13 'Asst OL 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(25, 8.33)

            Case 14 'DL 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(35, 8.33)

            Case 15 'Asst DL 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(25, 8.33)

            Case 16, 17  'ILB 1/OLB 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(35, 8.33)

            Case 18 'DB 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(40, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(35, 8.33)

            Case 19 'Asst DB 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(60, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(25, 8.33)

            Case 20 'Off QC 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(10, 3.333)

            Case 21 'Def QC 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(15, 5.0)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(10, 3.33)

            Case 22 'Str & Conditioning 1
                coachDT.Rows(i).Item("LowerBodyTrain") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("UpperBodyTrain") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("CoreTrain") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("PreventInjuryTrain") = MT.GetGaussian(75, 8.33)
                coachDT.Rows(i).Item("StaminaTrain") = MT.GetGaussian(75, 8.33)
            Case 23 'Asst Str & Cond 2-4
                coachDT.Rows(i).Item("LowerBodyTrain") = MT.GetGaussian(50, 8.33)
                coachDT.Rows(i).Item("UpperBodyTrain") = MT.GetGaussian(50, 8.33)
                coachDT.Rows(i).Item("CoreTrain") = MT.GetGaussian(50, 8.33)
                coachDT.Rows(i).Item("PreventInjuryTrain") = MT.GetGaussian(50, 8.33)
                coachDT.Rows(i).Item("StaminaTrain") = MT.GetGaussian(50, 8.33)
            Case 24 'Off Assistant 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(30, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(15, 5.0)

            Case 25 'Def Assistant 1
                coachDT.Rows(i).Item("OffAbility") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DefAbility") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("CoachDL") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachLB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachDB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("CoachST") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("JudgingDL") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingLB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingCB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("JudgingSF") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevQB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevRB") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevWR") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevTE") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevOL") = MT.GetGaussian(25, 8.33)
                coachDT.Rows(i).Item("DevDL") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevLB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevCB") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("DevSF") = MT.GetGaussian(35, 8.33)
                coachDT.Rows(i).Item("SeesBigPicture") = MT.GetGaussian(30, 8.33)
                coachDT.Rows(i).Item("PlaycallingSkill") = MT.GetGaussian(15, 5.0)

        End Select
    End Sub
    ''' <summary>
    ''' Determines what side of the ball they are most versed in...if a Head Coach gets fired, he will remain on the proper side of the ball---Ie, Offensive HC will become OC or Offensive Position coach, not DC or defensive position coach...
    ''' </summary>
    ''' <param name="CoachType"></param>
    ''' <returns></returns>
    Private Function GetSideOfBall(ByVal coachType As Integer) As String
        Dim Result As String = ""
        Select Case coachType
            Case 1, 2
                Dim Num As Integer = MT.GenerateInt32(1, 100)
                If Num < 45 Then
                    Result = "'OFF'"
                ElseIf Num < 91 Then
                    Result = "'DEF'"
                Else
                    Result = "'SPT'"
                End If
            Case 3, 7 To 13, 20, 24
                Result = "'OFF'"
            Case 4, 14 To 19, 21, 25
                Result = "'DEF'"
            Case 5, 6
                Result = "'SPT'"
            Case 22, 23
                Result = "'STC'"
        End Select
        Return Result
    End Function
    ''' <summary>
    ''' Head Coaches need to be older with more experience--minimum 10 years, as do OC and DC's
    ''' </summary>
    ''' <param name="age"></param>
    ''' <returns></returns>
    Private Function GetCoachType(age As Integer) As Integer
        Dim Result As Integer
        Select Case age
            Case < 29 'younger coaches start at low level positions
                Result = MT.GenerateInt32(20, 25)
                Do While Result = 22
                    Result = MT.GenerateInt32(20, 25)
                Loop
            Case < 36
                Result = MT.GenerateInt32(6, 25)
            Case Else 'Older coaches are not going to be in low level positions...
                Result = MT.GenerateInt32(1, 20)
                If Result = 20 Then Result = 22 'Strength and Conditioning coach is 22
        End Select
        Return Result
    End Function
    ''' <summary>
    ''' Cycle through the list of coaches and put them on teams
    ''' </summary>
    Public Sub PutCoachesOnTeams(ByVal coachDT As DataTable)
        Dim GetRow As Integer
        Try
            For Team As Integer = 1 To 32
                For CoachType As Integer = 1 To 25
                    GetRow = MT.GenerateInt32(0, coachDT.Rows.Count - 1)
                    Do While (coachDT.Rows(GetRow).Item("CoachType") <> CoachType) Or (coachDT.Rows(GetRow).Item("TeamID") <> 0)
                        GetRow = MT.GenerateInt32(0, coachDT.Rows.Count - 1)
                    Loop

                    coachDT.Rows(GetRow).Item("TeamID") = Team

                Next CoachType
            Next Team
        Catch ex As System.InvalidCastException
            Console.WriteLine(ex.Message)
            Console.WriteLine(ex.Data)
        End Try
    End Sub

End Class