'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class SharedResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GlobalResources.SharedResources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Arizona_Cardinals() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arizona_Cardinals", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Arizona_Cardinals_Helmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arizona_Cardinals_Helmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Arizona_Cardinals2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arizona_Cardinals2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property ArizonaCardinals3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArizonaCardinals3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property ArrowheadStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowheadStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Atlanta_Falcons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Atlanta_Falcons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Atlanta_Falcons_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Atlanta_Falcons_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Atlanta_Falcons2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Atlanta_Falcons2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property ATTStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ATTStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Baltimore_Ravens() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Baltimore_Ravens", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Baltimore_Ravens_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Baltimore_Ravens_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Baltimore_Ravens3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Baltimore_Ravens3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property BankOfAmericaStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BankOfAmericaStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property BillsDareusWilliams() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillsDareusWilliams", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property BillsFans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillsFans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property BillsFans2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillsFans2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property BillsFans3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillsFans3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property BillsGreats() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillsGreats", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property BillsLondon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillsLondon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property BillsMcCoy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillsMcCoy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property BillsMcCoy2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillsMcCoy2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property BillsOneBuffalo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillsOneBuffalo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property BillsPassRush() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillsPassRush", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property BillsTaylor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillsTaylor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property BillsWatkinsTaylor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillsWatkinsTaylor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Buffalo_Bills() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Buffalo_Bills", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Buffalo_Bills_PHelmet_2011() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Buffalo_Bills_PHelmet_2011", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Buffalo_Bills02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Buffalo_Bills02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Buffalo_Bills3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Buffalo_Bills3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Carolina_Panthers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carolina_Panthers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Carolina_Panthers_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carolina_Panthers_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Carolina_Panthers2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carolina_Panthers2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property CenturyLinkField() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CenturyLinkField", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Chicago_Bears() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chicago_Bears", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Chicago_Bears_PHelmet2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chicago_Bears_PHelmet2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Chicago_Bears4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chicago_Bears4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Cincinnati_Bengals() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cincinnati_Bengals", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Cincinnati_Bengals_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cincinnati_Bengals_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Cincinnati_Bengals3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cincinnati_Bengals3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Cleveland_Browns() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cleveland_Browns", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Cleveland_Browns_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cleveland_Browns_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Cleveland_Browns2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cleveland_Browns2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property ClevelandBrowns2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClevelandBrowns2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Dallas_Cowboys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dallas_Cowboys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Dallas_Cowboys_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dallas_Cowboys_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Dallas_Cowboys3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dallas_Cowboys3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Denver_Broncos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Denver_Broncos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Denver_Broncos_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Denver_Broncos_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Denver_Broncos2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Denver_Broncos2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Detroit_Lions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Detroit_Lions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Detroit_Lions_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Detroit_Lions_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Detroit_Lions3a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Detroit_Lions3a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property DetroitLions2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DetroitLions2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property DolphinsCelebrate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DolphinsCelebrate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property DolphinsGreats() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DolphinsGreats", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property DolphinsMiller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DolphinsMiller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property DolphinsPreSnap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DolphinsPreSnap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property DolphinsRushing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DolphinsRushing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property DolphinsStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DolphinsStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property DolphinsTannehill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DolphinsTannehill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property DolphinsTannehill2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DolphinsTannehill2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property DolphinsTouchdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DolphinsTouchdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property DolphinsTrainingCamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DolphinsTrainingCamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property EverBankField() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EverBankField", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property fedex_field() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fedex_field", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property FirstEnergyStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FirstEnergyStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property footballfield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("footballfield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property FootballGoalLine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FootballGoalLine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property fordfield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fordfield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Georgia_Dome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Georgia_Dome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property georgia_dome1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("georgia_dome1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property gillette_stadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gillette_stadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Green_Bay_Packers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Green_Bay_Packers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Green_Bay_Packers_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Green_Bay_Packers_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Green_Bay_Packers5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Green_Bay_Packers5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property HeinzField() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeinzField", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Houston_Texans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Houston_Texans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Houston_Texans_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Houston_Texans_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Houston_Texans2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Houston_Texans2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Indianapolis_Colts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Indianapolis_Colts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Indianapolis_Colts_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Indianapolis_Colts_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Indianapolis_Colts2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Indianapolis_Colts2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Jacksonville_Jaguars_2013a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jacksonville_Jaguars_2013a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Jacksonville_Jaguars_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jacksonville_Jaguars_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Jacksonville_Jaguars2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jacksonville_Jaguars2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property JetsDecker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetsDecker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property JetsFans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetsFans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property JetsFitz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetsFitz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property JetsIvory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetsIvory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property JetsMarshall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetsMarshall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property JetsMarshall2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetsMarshall2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property JetsMinicamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetsMinicamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property JetsOverPile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetsOverPile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property JetsTouchdown2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetsTouchdown2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property JetsTunnel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetsTunnel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property JetsWallpaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetsWallpaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Kansas_City_Chiefs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kansas_City_Chiefs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Kansas_City_Chiefs_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kansas_City_Chiefs_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Kansas_City_Chiefs3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kansas_City_Chiefs3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property lambeaufield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lambeaufield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property LARams() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LARams", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property LARams1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LARams1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property levis_stadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("levis_stadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property LincolnFinancialField() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LincolnFinancialField", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property LosAngelesColiseum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LosAngelesColiseum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property LucasOilStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LucasOilStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property M_TBankStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("M_TBankStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property MetLife_Stadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MetLife_Stadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Miami_Dolphins_2013() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Miami_Dolphins_2013", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Miami_Dolphins_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Miami_Dolphins_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Miami_Dolphins2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Miami_Dolphins2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Minnesota_Vikings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minnesota_Vikings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Minnesota_Vikings_2013_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minnesota_Vikings_2013_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Minnesota_Vikings_PHelmet_2013() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minnesota_Vikings_PHelmet_2013", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property New_England_Patriots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_England_Patriots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property New_England_Patriots_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_England_Patriots_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property New_England_Patriots2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_England_Patriots2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property New_Orleans_Saints() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_Orleans_Saints", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property New_Orleans_Saints_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_Orleans_Saints_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property New_Orleans_Saints2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_Orleans_Saints2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property New_York_Giants() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_York_Giants", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property New_York_Giants_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_York_Giants_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property New_York_Giants5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_York_Giants5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property New_York_Jets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_York_Jets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property New_York_Jets_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_York_Jets_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property New_York_Jets2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_York_Jets2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property NFLWallpaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NFLWallpaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property NFLWallpaper2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NFLWallpaper2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property NissanStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NissanStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property NRGStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NRGStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Oakland_Raiders() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Oakland_Raiders", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Oakland_Raiders_Helmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Oakland_Raiders_Helmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Oakland_Raiders_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Oakland_Raiders_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property OaklandColiseum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OaklandColiseum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PatriotsBelichick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatriotsBelichick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PatriotsBrady() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatriotsBrady", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PatriotsBradyGronk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatriotsBradyGronk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PatriotsCelebrate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatriotsCelebrate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PatriotsDefense() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatriotsDefense", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PatriotsEdelman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatriotsEdelman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PatriotsFans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatriotsFans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PatriotsGreats() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatriotsGreats", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PatriotsGronk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatriotsGronk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PatriotsReceivers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatriotsReceivers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PatriotsSuperBowl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatriotsSuperBowl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PatriotsTunnel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatriotsTunnel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PaulBrownStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PaulBrownStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Philadelphia_Eagles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Philadelphia_Eagles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Philadelphia_Eagles_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Philadelphia_Eagles_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Philadelphia_Eagles2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Philadelphia_Eagles2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Pittsburgh_Steelers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pittsburgh_Steelers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Pittsburgh_Steelers_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pittsburgh_Steelers_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Pittsburgh_Steelers2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pittsburgh_Steelers2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Pittsburgh_Steelers3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pittsburgh_Steelers3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property QualcommStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QualcommStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property RalphWilsonStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RalphWilsonStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property RaymondJamesStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaymondJamesStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property San_Diego_Chargers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("San_Diego_Chargers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property San_Diego_Chargers_PHelmet2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("San_Diego_Chargers_PHelmet2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property San_Diego_Chargers5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("San_Diego_Chargers5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property San_Francisco_49ers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("San_Francisco_49ers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property San_Francisco_49ers_PHelmet_New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("San_Francisco_49ers_PHelmet_New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property San_Francisco_49ers04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("San_Francisco_49ers04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bye Week Configuration: #10(4 weeks--2 Bye Teams, 3 Weeks--4 Bye teams, 2 weeks--6 Bye Teams)
        '''-----------------------
        '''WEEK 1 SCHEDULE
        '''-----------------------
        '''
        '''BUF(1) vs. NWE(2)
        '''NYJ(3) vs. BAL(7)
        '''MIA(4) vs. SEA(30)
        '''CIN(5) vs. DAL(20)
        '''PIT(6) vs. KC (14)
        '''TEN(12) vs. CLE(8)
        '''HOU(9) vs. MIN(21)
        '''IND(10) vs. JAX(11)
        '''DEN(13) vs. OAK(15)
        '''SD (16) vs. ATL(26)
        '''GB (22) vs. WAS(17)
        '''PHI(18) vs. CHI(24)
        '''NWO(27) vs. NYG(19)
        '''LAR(31) vs. DET(23)
        '''ARI(29) vs. CAR(25)
        '''SFO(32) vs. TAM(28)
        '''--------------------- [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property Schedule4GamesMax() As String
            Get
                Return ResourceManager.GetString("Schedule4GamesMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Seattle_Seahawks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Seattle_Seahawks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Seattle_Seahawks_PHelmet_2012() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Seattle_Seahawks_PHelmet_2012", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Seattle_Seahawks2_2012() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Seattle_Seahawks2_2012", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property SoldierField() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SoldierField", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Sports_Authority_Field() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sports_Authority_Field", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property SportsAuthorityField() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SportsAuthorityField", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property SunLifeStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SunLifeStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property superdome_saints() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("superdome_saints", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Tampa_Bay_Buccaneers_2014() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tampa_Bay_Buccaneers_2014", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Tampa_Bay_Buccaneers_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tampa_Bay_Buccaneers_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Tampa_Bay_Buccaneers2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tampa_Bay_Buccaneers2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Tennessee_Titans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tennessee_Titans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Tennessee_Titans_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tennessee_Titans_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Tennessee_Titans2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tennessee_Titans2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property university_of_phoenix_stadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("university_of_phoenix_stadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property university_phoenix_stadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("university_phoenix_stadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property USBankStadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("USBankStadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Washington_Redskins() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Washington_Redskins", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Washington_Redskins_PHelmet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Washington_Redskins_PHelmet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Washington_Redskins2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Washington_Redskins2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property WashingtonRedskins3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WashingtonRedskins3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
